language: node_js
node_js:
  - "7"
apt:
 sources:
 — google-chrome
 packages:
 — google-chrome-stable
 — google-chrome-beta
before_install:
  - cp .env.client.sample.ts .env.client.ts
  - cp .env.sample .env